### ISSUE TITLE
Getting error when trying to access a subdomain in .dugway.json 

### ISSUE THREAD

**Issue by julianomoreira** [bigcartel-themes/picklejuice#130]
I'm using the correct subdomain but I get this error: 

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:176:in `split': bad URI(is not URI?): http://api.bigcartel.com/{"subdomain"=>"missmelo"}/store.json (URI::InvalidURIError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:211:in `parse'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:747:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/httparty-0.10.2/lib/httparty/request.rb:56:in `uri'
	from /Library/Ruby/Gems/2.0.0/gems/httparty-0.10.2/lib/httparty/request.rb:143:in `setup_raw_request'
	from /Library/Ruby/Gems/2.0.0/gems/httparty-0.10.2/lib/httparty/request.rb:88:in `perform'
	from /Library/Ruby/Gems/2.0.0/gems/httparty-0.10.2/lib/httparty.rb:456:in `perform_request'
	from /Library/Ruby/Gems/2.0.0/gems/httparty-0.10.2/lib/httparty.rb:398:in `get'
	from /Library/Ruby/Gems/2.0.0/gems/dugway-0.10.2/lib/dugway/store.rb:131:in `get'
	from /Library/Ruby/Gems/2.0.0/gems/dugway-0.10.2/lib/dugway/store.rb:16:in `account'
	from /Library/Ruby/Gems/2.0.0/gems/dugway-0.10.2/lib/dugway/store.rb:121:in `currency'
	from /Library/Ruby/Gems/2.0.0/gems/dugway-0.10.2/lib/dugway/store.rb:125:in `locale'
	from /Library/Ruby/Gems/2.0.0/gems/dugway-0.10.2/lib/dugway.rb:35:in `application'
	from /Users/julianomoreira/Code/picklejuice/config.ru:12:in `block in <main>'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
	from /Users/julianomoreira/Code/picklejuice/config.ru:in `new'
	from /Users/julianomoreira/Code/picklejuice/config.ru:in `<main>'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.4.5/lib/rack/builder.rb:40:in `eval'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.4.5/lib/rack/builder.rb:40:in `parse_file'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.4.5/lib/rack/server.rb:200:in `app'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.4.5/lib/rack/server.rb:304:in `wrapped_app'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.4.5/lib/rack/server.rb:254:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.4.5/lib/rack/server.rb:137:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/dugway-0.10.2/lib/dugway/cli/server.rb:25:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.17.0/lib/thor/task.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.17.0/lib/thor/invocation.rb:120:in `invoke_task'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `block in invoke_all'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `map'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `invoke_all'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.17.0/lib/thor/group.rb:238:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.17.0/lib/thor/invocation.rb:109:in `invoke'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.17.0/lib/thor.rb:32:in `block in register'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.17.0/lib/thor/task.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.17.0/lib/thor/invocation.rb:120:in `invoke_task'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.17.0/lib/thor.rb:344:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.17.0/lib/thor/base.rb:434:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/dugway-0.10.2/bin/dugway:7:in `<top (required)>'
	from /usr/bin/dugway:23:in `load'
	from /usr/bin/dugway:23:in `<main>'

**Comment by nickendle** [comment]
@julianomoreira in order to use the new .dugway.json format you'll need to upgrade your version of Dugway, right now you're at 0.10.2 but the current version is 0.10.3 https://github.com/bigcartel/dugway/blob/master/CHANGELOG.md

`gem update dugway` should do the trick.

**Comment by julianomoreira** [comment]
Thanks! Appreciated.
